### PR TITLE
Get rid of Iris and use julienschmidt/httprouter instead

### LINKED ISSUE #11: Complete rewrite of api tests
HTTP API tests need complete rewrite because of Iris framework changes regarding testing. See 41b2ff5940acf3fcbaa2f3799ac284344d5655f9 which removed the broken tests.

### LINKED ISSUE #16: Rewrite HTTP API to get rid of Iris
The very light usage of HTTP API features can be done using something a lot more lightweight than Iris. The framework also has hard time keeping a stable API, so it causes a lot of unnecessary work.

### PR DESCRIPTION
**Pull request by joohoi**
Iris can't keep the API stable, and while looking into it, found out a lot of drama behind the scenes too. This change will also rid us of hefty dependency stack brought in by iris.

Brought back the HTTP api tests as well!

Fixes #16 
Fixes #11

### CODE REVIEW

File: api.go [hunk 1]
```diff
@@ -1,115 +1,80 @@
...
+func webRegisterPost(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
 	var regStatus int
+	var reg []byte
 	aTXT := ACMETxt{}
-	_ = ctx.ReadJSON(&aTXT)
+	if r.Body == nil {
+		http.Error(w, string(jsonError("body_missing")), http.StatusBadRequest)
+		return
+	}
+	json.NewDecoder(r.Body).Decode(&aTXT)
```
Comment (koesie10) [inline api.go:29]: The error return value is not checked here, is this on purpose to allow empty POST bodies?

Comment (joohoi) [reply api.go:29]: It indeed is the idea to allow empty POST bodies, as the only parameter for registration, "allowfrom" is optional. 

You have good eyes though, as the body check shouldn't be there, even though it's really not completely empty in pretty much any real world situation.

Comment (koesie10) [reply api.go:29]: That is also a good point, however I was actually talking about the return value of Decode, which can be an error and is not checked in this case, which means that there is no indication that invalid JSON was sent. Of course, when you check it and the body is empty, it will return an error (probably EOF), so that should still be allowed.

Comment (joohoi) [reply api.go:29]: Let's continue the discussion on issue #23 so it doesn't get buried to the PR graveyard.
